### ISSUE TITLE
Making cleaning up easy...

### ISSUE THREAD

**Issue by crumleyc** [DigiUGA/UGA-Dissertation-LaTeX-Template#1]
As I am working on these files with compiling and then having to delete the ten or so files, I am making a short cut in my command line so I don't have to keep doing it. 

I think this brings up a good question before we get started on tutorials and thinking about what are we going to teach about as an editing tool? I use atom, I know Jonathan uses vim. I know that when you have LaTeX installed the commands to compile are `pdflatex <filename.tex>` and something similar for the bibliography. Should we introduce the command line? Push people to Overleaf where everything is online and they dont have to worry about it? I think I have already brought this up, but i dont remember the discussion. Thoughts?

I was just thinking about making an official thing that would be a simple command. If we teach it in the command line, then a simple makefile or bash script would handle compile and cleaning. 

Definitely not important, but for convenience.

**Comment by krummja** [comment]
It's not so much X amount of pages as it is X amount of compilation time, which can be really any number of pages depending on complexity.

As far as what to cover, I was thinking more discussion of use cases that pair with certain document types, e.g. using latex as a lab notebook, as a research journal, for class notes, etc.

I'm also considering talking a bit on something I've been playing with lately, which is literate programming in emacs. Basically I can write notes and interleave my notes with code blocks that I can have emacs (using babel) tangle to an external file. I use this for my configuration dotfiles for emacs itself, but I really want to try a workflow of notetaking where i just draft my latex directly in the note file, compile, and render PDF.

**Comment by crumleyc** [comment]
I also starred a repo that was a pluggin for Tex in vim. https://github.com/lervag/vimtex I was gonna send this to you at some point. Im not familar with using vim, so I wasn't sure about if it was useful for you or at all. 

I was just thinking that it would be important to layout some options of the environment, other than overleaf.

**Comment by krummja** [comment]
Yeah, vimtex is pretty great. Glad you ran across it.

My [vim configuration](https://github.com/krummja/.cfg/blob/master/.vimrc) uses vimtex as well as [vim-latex-live-preview](https://github.com/xuhdev/vim-latex-live-preview) for direct compiling.
