### ISSUE TITLE
List of references

### ISSUE THREAD

**Issue by crumleyc** [DigiUGA/UGA-Dissertation-LaTeX-Template#2]
Labeling and referencing: https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing

**Comment by krummja** [comment]
The [Overleaf documentation](https://www.overleaf.com/learn/latex/Main_Page) is pretty comprehensive, as well.

**Comment by crumleyc** [comment]
For the Bibliography: https://www2.cs.arizona.edu/~collberg/Teaching/07.231/BibTeX/bibtex.html
