### ISSUE TITLE
Mulitiple Language Capabilities

### ISSUE THREAD

**Issue by crumleyc** [DigiUGA/UGA-Dissertation-LaTeX-Template#3]
Emily and I were just discussing LaTeX's capabilities with different languages. I am going to include multiple examples of citations, and figured might as well include some of them in the bibliography. That also got me thinking about in general. How can we make these documents work if the entire thing was written in another language other than english. How can we tell the compiler that this document consist of multiple languages? 

Thoughts on how to approach this? Y'all got any experience? I don't. 

https://tex.stackexchange.com/questions/96469/switching-languages-in-bibliography-with-biblatex --> Allowing for different languages to be in the bibliography. Have not tried it, will update.  I will also post other links of solutions that I have had worked for me.

**Comment by crumleyc** [comment]
https://www.ctan.org/pkg/babel

**Comment by krummja** [comment]
Yeah babel is a good one. One year for the linguistics conference I had to typeset Mandarin Chinese... so there's always a way.

As far as specific support, I don't think UGA permits dissertations to be published in languages other than English, do they? Otherwise I would just point them towards specific resources.

**Comment by crumleyc** [comment]
My thinking with this was maybe the references might be in a different language or they may need to quote in a different language. When I was looking up ideas, I remember I found a thread that allowed you to specify at the time of use that this next bit will be in another language, other than the default.

**Comment by crumleyc** [comment]
I am currently looking at two things:
1. How can out Bibliography contain multiple languages and how does citing them work
2. What about footnotes being in different languages
