### ISSUE TITLE
Template Class File?

### ISSUE THREAD

**Issue by krummja** [DigiUGA/UGA-Dissertation-LaTeX-Template#4]
So one thing I was wanting to do for this project was to put the document configurations in a separate class file, that way our distribution will just be a single file that the user doesn't even really have to mess around with.

It's apparently pretty easy to define class options so that when you declare your documentclass, you can just pass in arguments that select the options. For example, if I wanted sidenotes and running headers, I might use:

`\documentclass[12pt sidenotes running]{uga}`

And that's all she wrote.

Thoughts?

**Comment by crumleyc** [comment]
As I was getting the current running version for the Grad School, I was thinking that most of the things I was adding to the preamble would be moved to the style sheet. If that is all that the user would have to change, then that would be the easiest way that I could see.
